

# This file was *autogenerated* from the file log_2_floor.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_20 = Integer(20); _sage_const_32 = Integer(32); _sage_const_33 = Integer(33); _sage_const_48 = Integer(48); _sage_const_64 = Integer(64); _sage_const_72 = Integer(72); _sage_const_80 = Integer(80); _sage_const_96 = Integer(96)
def log2_ceil(D):
    D = ZZ(D)
    if D <= _sage_const_0 :
        raise ValueError("D must be ≥ 1")
    if D == _sage_const_1 :
        return _sage_const_0 
    # ceil(log2 D) = floor(log2(D-1)) + 1 = (D-1).nbits()
    return (D - _sage_const_1 ).nbits()

def dlf_bound_hfe(D):
    """Theorem bound for HFE over F_{2^n}."""
    t = log2_ceil(D)
    return t + _sage_const_2 

# demo
for D in [_sage_const_1 ,_sage_const_2 ,_sage_const_3 ,_sage_const_6 ,_sage_const_8 ,_sage_const_16 ,_sage_const_20 ,_sage_const_32 ,_sage_const_33 ,_sage_const_48 ,_sage_const_64 ,_sage_const_72 ,_sage_const_80 ,_sage_const_96 ]:
    print(f"D={D:>3}  t=ceil(log2 D)={log2_ceil(D)}  bound d_lf ≤ {dlf_bound_hfe(D)}")


