

# This file was *autogenerated* from the file scripts/process_bool_elimlin.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8)# Preprocess Boolean MQ: multilinearize mod <x_i^2+x_i>, one-shot ElimLin via
# quadratic cancellation, then eliminate linear vars by GF(2) Gaussian elim.
# Usage: sage scripts/process_bool_elimlin.sage data/HFE_n80_D96.in

import sys, os, json
from sage.all import GF, PolynomialRing, matrix

def ensure_dir(p):
    if not os.path.exists(p): os.makedirs(p)

def stem(p): return os.path.splitext(os.path.basename(p))[_sage_const_0 ]

def read_infile(path):
    with open(path) as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    vars_ = [v.strip() for v in lines[_sage_const_0 ].split(",")]
    fld = lines[_sage_const_1 ]
    if fld.upper().startswith("GF("):
        inside = fld.split("GF(",_sage_const_1 )[_sage_const_1 ].split(")",_sage_const_1 )[_sage_const_0 ]
        p = int(inside.split("^",_sage_const_1 )[_sage_const_0 ]) if "^" in inside else int(inside)
    else:
        p = int(fld)
    polys = lines[_sage_const_2 :]
    return vars_, p, polys

def write_infile(path, vars_, p, polys, add_field_eqs=True):
    with open(path, "w") as out:
        out.write(", ".join(vars_) + "\n")
        out.write(f"{p}\n")
        for s in polys:
            out.write(s + "\n")
        if add_field_eqs:
            for v in vars_:
                out.write(f"{v}^2 + {v}\n")

def _is_bool_field_eq(f):
    if f.total_degree() != _sage_const_2 : return False
    mons = f.monomials()
    if len(mons) != _sage_const_2 : return False
    if any(c != _sage_const_1  for c in f.coefficients()): return False
    vs = f.variables()
    if len(vs) != _sage_const_1 : return False
    v = vs[_sage_const_0 ]
    return set(mons) == {v, v**_sage_const_2 }

# -------- Boolean reduction without quotient rings (portable) ----------
def boolean_reduce_poly_multilinear(f):
    """Reduce f modulo <x_i^2+x_i> over GF(2) by multilinearizing terms."""
    R = f.parent()
    gens = R.gens()
    acc = {}  # exponent tuple -> coeff in GF(2)
    for exps, coeff in f.dict().items():
        if coeff == _sage_const_0 : continue
        new_exps = tuple(_sage_const_1  if e > _sage_const_0  else _sage_const_0  for e in exps)
        acc[new_exps] = (acc.get(new_exps, R.base_ring()(_sage_const_0 )) + coeff)
    g = R(_sage_const_0 )
    for exps, c in acc.items():
        if c == _sage_const_0 : continue
        mon = R(_sage_const_1 )
        for gi, e in zip(gens, exps):
            if e: mon *= gi
        g += c*mon
    return g

def polys_boolean_reduce(P):
    return [boolean_reduce_poly_multilinear(f) for f in P]

# ----------------------------------------------------------------------

def collect_linear_equations(P, var_order):
    if not P: return None, []
    R = var_order[_sage_const_0 ].parent()
    rows, eqs = [], []
    for f in P:
        f = R(f)
        if f.total_degree() <= _sage_const_1 :
            coeffs = [int(f.coefficient(v)) & _sage_const_1  for v in var_order]
            cst = int(f.constant_coefficient()) & _sage_const_1 
            if any(coeffs) or cst:
                rows.append(coeffs + [cst])
                eqs.append(f)
    if not rows:
        return None, []
    A = matrix(GF(_sage_const_2 ), rows)
    return A, eqs

def rref_linear_solutions(A, var_order):
    RREF = A.rref()
    nvars = A.ncols() - _sage_const_1 
    sol = {}
    for r in range(RREF.nrows()):
        row = RREF.row(r)
        j = None
        for c in range(nvars):
            if int(row[c]) == _sage_const_1  and all(int(RREF[k,c]) == _sage_const_0  for k in range(RREF.nrows()) if k != r):
                j = c; break
        if j is None: 
            continue
        const = int(row[nvars]) & _sage_const_1 
        lin = {}
        for i in range(nvars):
            if i == j: continue
            if int(row[i]) & _sage_const_1 :
                lin[str(var_order[i])] = _sage_const_1 
        sol[str(var_order[j])] = {'lin': lin, 'c': const}
    return sol

def _lookup_var(name, R):
    for g in R.gens():
        if str(g) == name: return g
    raise KeyError(name)

def substitute_linear_map(P, linmap, R):
    subs = {}
    for vname, desc in linmap.items():
        expr = R(_sage_const_0 )
        for wname in desc['lin'].keys():
            expr += _lookup_var(wname, R)
        if desc['c'] & _sage_const_1 :
            expr += R(_sage_const_1 )
        subs[_lookup_var(vname, R)] = expr
    return [f.subs(subs) for f in P]

def oneshot_elimlin_qcancel(P, x):
    """
    One-shot ElimLin via quadratic cancellation:
    Build matrix of coefficients of xi*xj (i<j), take left kernel, and keep
    any resulting non-zero linear combinations.
    """
    if not P: return []
    R = x[_sage_const_0 ].parent(); F2 = GF(_sage_const_2 )
    n = len(x)
    Q = [x[i]*x[j] for i in range(n) for j in range(i+_sage_const_1 , n)]
    if not Q: return []
    A = matrix(F2, len(P), len(Q))
    for r, f in enumerate(P):
        f = R(f)
        for c, mon in enumerate(Q):
            if int(f.monomial_coefficient(mon)) & _sage_const_1 :
                A[r, c] = _sage_const_1 
    L = A.left_kernel()
    if L.dimension() == _sage_const_0 :
        return []
    P_int = [R(g) for g in P]
    new_lin = []
    for v in L.basis():
        g = R(_sage_const_0 )
        for i, coeff in enumerate(v):
            if int(coeff) & _sage_const_1 :
                g += P_int[i]
        g = boolean_reduce_poly_multilinear(g)
        if g != _sage_const_0  and g.total_degree() <= _sage_const_1 :
            new_lin.append(g)
    new_lin = list(dict.fromkeys(map(str, new_lin)))
    return [R(s) for s in new_lin]

def main():
    if len(sys.argv) < _sage_const_2 :
        print("Usage: sage scripts/process_bool_elimlin.sage <input.in>")
        sys.exit(_sage_const_1 )
    infile = sys.argv[_sage_const_1 ]
    vars_, p, polys_str = read_infile(infile)
    if p != _sage_const_2 :
        print(f"[WARN] Field is GF({p}); this preprocessor is tuned for GF(2). Proceeding anyway.")

    # Build ring
    F = GF(p)
    R = PolynomialRing(F, vars_, order='degrevlex')
    x = R.gens()

    # Parse polynomials and drop explicit field eqs
    P = [R(s) for s in polys_str]
    P = [f for f in P if not _is_bool_field_eq(f)]

    # Boolean reduce all
    P = polys_boolean_reduce(P)

    # One-shot ElimLin via quadratic cancellation
    new_lin = oneshot_elimlin_qcancel(P, x)
    if new_lin:
        P = polys_boolean_reduce(P + new_lin)
        P = [f for f in P if f != _sage_const_0 ]
        P = [R(s) for s in dict.fromkeys(map(str, P)).keys()]

    # Iterative linear elimination
    eliminated = {}   # vname -> {'lin':{w:1}, 'c':0/1}
    max_iters = _sage_const_8 
    it = _sage_const_0 
    var_order = list(reversed([R(str(v)) for v in vars_]))  # prefer higher indices
    while it < max_iters:
        A, eqs = collect_linear_equations(P, var_order)
        if A is None: break
        linmap = rref_linear_solutions(A, var_order)
        newmap = {v:desc for v,desc in linmap.items() if v not in eliminated}
        if not newmap: break

        # Compose with previous map so expressions refer to truly-free vars
        def expr_from_map(desc):
            e = R(_sage_const_0 )
            for w in desc['lin'].keys(): e += _lookup_var(w, R)
            if desc['c'] & _sage_const_1 : e += _sage_const_1 
            return e
        subs_prev = { _lookup_var(v, R): expr_from_map(desc) for v,desc in eliminated.items() }

        newmap_composed = {}
        for v, desc in newmap.items():
            e = expr_from_map(desc).subs(subs_prev)
            lin = {}
            for g in R.gens():
                if int(R(e).coefficient(g)) & _sage_const_1 : lin[str(g)] = _sage_const_1 
            c = int(R(e).constant_coefficient()) & _sage_const_1 
            newmap_composed[v] = {'lin': lin, 'c': c}

        eliminated.update(newmap_composed)
        P = substitute_linear_map(P, newmap_composed, R)
        P = polys_boolean_reduce(P)
        P = [f for f in P if f != _sage_const_0 ]
        P = [R(s) for s in dict.fromkeys(map(str, P)).keys()]
        it += _sage_const_1 

    # Remaining (free) variables
    free_vars = [v for v in vars_ if v not in eliminated]

    # Re-express P over ring in free variables
    R2 = PolynomialRing(F, free_vars, order='degrevlex')
    name2var = { str(g):g for g in R2.gens() }
    subs_to_free = {}
    for g in R.gens():
        s = str(g)
        if s in eliminated:
            e = _sage_const_0 
            for w in eliminated[s]['lin'].keys(): e += name2var[w]
            if eliminated[s]['c'] & _sage_const_1 : e += _sage_const_1 
            subs_to_free[g] = R(e)
        else:
            subs_to_free[g] = R(name2var[s])
    P_free = [ R2(R(f).subs(subs_to_free)) for f in P ]

    # Outputs
    ensure_dir("results"); ensure_dir("logs")
    st = stem(infile)
    out_in  = f"results/{st}_preproc.in"
    out_map = f"results/{st}_preproc_map.json"
    out_log = f"logs/{st}_preproc.log"

    write_infile(out_in, free_vars, p, [str(f) for f in P_free], add_field_eqs=True)
    with open(out_map, "w") as m:
        json.dump({"original_vars": vars_,
                   "free_vars": free_vars,
                   "eliminated": eliminated}, m, indent=_sage_const_2 )
    with open(out_log, "w") as L:
        L.write(f"Preprocess summary for {infile}\n")
        L.write(f"Original vars: {len(vars_)} -> Free vars: {len(free_vars)} (eliminated {len(eliminated)})\n")
        if new_lin:
            L.write(f"One-shot ElimLin (quadratic cancel): found {len(new_lin)} new linear equation(s).\n")
        else:
            L.write("One-shot ElimLin (quadratic cancel): found 0 new linear equations.\n")
        if eliminated:
            L.write("Eliminated pivots:\n")
            for v,desc in eliminated.items():
                xs = " + ".join(sorted(desc['lin'].keys())) or "0"
                L.write(f"  {v} = {xs} {'+ 1' if desc['c'] else ''}\n")
        else:
            L.write("No linear pivots eliminated.\n")

    print(f"[OK] Wrote reduced instance: {out_in}")
    print(f"[OK] Wrote mapping:          {out_map}")
    print(f"[OK] Log:                    {out_log}")

if __name__ == "__main__":
    main()

