

# This file was *autogenerated* from the file scripts/system_diagnosis.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2)
import sys

def parse_input_system(filename):
    with open(filename) as f:
        lines = [l.strip() for l in f if l.strip() and not l.strip().startswith('#')]
    var_names = [v.strip() for v in lines[_sage_const_0 ].split(',')]
    field_line = lines[_sage_const_1 ]
    if "^" in field_line:
        p, n = [int(x.strip()) for x in field_line.split("^")]
        F = GF(p**n, 'a')
        field_desc = f"GF({p}^{n})"
    else:
        p = int(field_line)
        F = GF(p)
        field_desc = f"GF({p})"
    polys = lines[_sage_const_2 :]
    return var_names, F, field_desc, polys

def is_homogeneous(poly):
    degs = [m.degree() for m in poly.monomials()]
    return len(set(degs)) == _sage_const_1 

def main():
    if len(sys.argv) < _sage_const_2 :
        print("Usage: sage diagnose_system.sage <input_file.in>")
        sys.exit(_sage_const_1 )
    infile = sys.argv[_sage_const_1 ]
    outlog = infile.replace(".in", "_diagnostics.log").replace("data/", "logs/")
    vars, F, field_desc, polys_str = parse_input_system(infile)
    R = PolynomialRing(F, vars)
    polynomials = [R(s) for s in polys_str]
    I = R.ideal(polynomials)
    log = []
    log.append(f"System: {infile}")
    log.append(f"Field: {field_desc}")
    log.append(f"Variables: {vars}")
    log.append(f"Number of variables: {len(vars)}")
    log.append(f"Number of equations: {len(polynomials)}")
    degs = [p.total_degree() for p in polynomials]
    log.append(f"Degrees of input polynomials: {degs}")
    log.append(f"Max degree: {max(degs)}, Min degree: {min(degs)}")
    terms = [len(p.monomials()) for p in polynomials]
    log.append(f"Sparsity: Terms per polynomial: {terms}")
    homog = [is_homogeneous(p) for p in polynomials]
    log.append(f"Homogeneous polynomials: {homog}")
    all_homog = all(homog)
    log.append(f"All polynomials homogeneous? {all_homog}")
    try:
        dim = I.dimension()
        log.append(f"Krull dimension of the ideal: {dim}")
        if dim == _sage_const_0 :
            log.append("System is zero-dimensional (finite number of solutions).")
        elif dim == -_sage_const_1 :
            log.append("Ideal is the unit ideal (1 in the basis).")
        else:
            log.append("System is positive-dimensional (infinitely many solutions).")
    except Exception as e:
        log.append(f"Could not compute dimension: {e}")
    # Ideal degree (Hilbert polynomial at zero for zero-dim)
    try:
        hilb = I.hilbert_polynomial()
        degI = hilb(_sage_const_0 ) if I.dimension() == _sage_const_0  else hilb.degree()
        log.append(f"Degree of the ideal (zero-dim: number of points, else: degree of Hilbert polynomial): {degI}")
    except Exception as e:
        log.append(f"Could not compute ideal degree (Hilbert polynomial): {e}")

    # No shape position/lex basis attempted!
    log.append("Shape position check skipped (lex Groebner basis not computed).")
    is_boolean = F.order() == _sage_const_2  and all(p.total_degree() <= _sage_const_2  for p in polynomials)
    log.append(f"System is Boolean quadratic? {'Yes' if is_boolean else 'No'}")
    is_quadratic = all(p.total_degree() <= _sage_const_2  for p in polynomials)
    log.append(f"System is quadratic (all degree ≤2)? {'Yes' if is_quadratic else 'No'}")
    # Save log
    with open(outlog, "w") as f:
        for line in log:
            print(line)
            f.write(line + "\n")
    print(f"\nDiagnostics saved to {outlog}")

main()

