

# This file was *autogenerated* from the file scripts/verify_pcico_solutions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)# Usage:
#   sage scripts/verify_pcico_solutions.sage --in data/ANEMOI_p251_r2_a3_PCICO.in \
#        --sols results/ANEMOI_p251_r2_a3_PCICO_F4_..._LEX_sols.txt

import sys, re

def parse_args(argv):
    infile = None
    solsfile = None
    i = _sage_const_1 
    while i < len(argv):
        a = argv[i]
        if a == "--in" and i+_sage_const_1  < len(argv):
            infile = argv[i+_sage_const_1 ]; i += _sage_const_2 
        elif a == "--sols" and i+_sage_const_1  < len(argv):
            solsfile = argv[i+_sage_const_1 ]; i += _sage_const_2 
        else:
            print(f"Unrecognized/missing arg near: {a}"); sys.exit(_sage_const_2 )
    if not infile or not solsfile:
        print("Usage: sage scripts/verify_pcico_solutions.sage --in <.in> --sols <*_LEX_sols.txt>")
        sys.exit(_sage_const_1 )
    return infile, solsfile

def parse_in_file(path):
    with open(path, "r") as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    var_names = [v.strip() for v in lines[_sage_const_0 ].split(",")]
    p = int(lines[_sage_const_1 ])
    F = GF(p)
    R = PolynomialRing(F, var_names, order='lex')  # order irrelevant for evaluation
    polys = [R(s) for s in lines[_sage_const_2 :]]
    return var_names, F, R, polys

def parse_solutions(path, F):
    sols = []
    with open(path, "r") as f:
        for ln in f:
            s = ln.strip()
            if not s or s.startswith("#"): 
                continue
            if s.startswith("{") and s.endswith("}"):
                # Turn "{Y0000: 170, S0200: 101, S0100: 215}" into dict
                pairs = [t.strip() for t in s[_sage_const_1 :-_sage_const_1 ].split(",")]
                d = {}
                for pr in pairs:
                    if not pr: 
                        continue
                    k, v = pr.split(":", _sage_const_1 )
                    key = k.strip()
                    val = int(v.strip())
                    d[key] = F(val)
                sols.append(d)
    return sols

def main():
    infile, solsfile = parse_args(sys.argv)
    var_names, F, R, polys = parse_in_file(infile)
    sols = parse_solutions(solsfile, F)

    print("== Verifying solutions against original PCICO polynomials ==")
    print(f"File: {infile}")
    print(f"Solutions: {solsfile}  (count={len(sols)})")
    ok_all = True
    for idx, d in enumerate(sols, _sage_const_1 ):
        # Build substitution map R.gen(i) -> value
        sub = { R(v): d[v] for v in var_names }
        fails = []
        for j, f in enumerate(polys, _sage_const_1 ):
            val = f.subs(sub)
            if val != _sage_const_0 :
                fails.append((j, val))
        if fails:
            ok_all = False
            print(f"[FAIL] solution #{idx}: {d}")
            for (j,val) in fails:
                print(f"   poly #{j} -> {val} (≠0)")
        else:
            print(f"[OK]   solution #{idx}: all {len(polys)} polynomials vanish.")
    if ok_all:
        print("All listed solutions satisfy the original PCICO system.")
    else:
        print("Some listed solutions did NOT satisfy the original equations. Inspect logs above.")

if __name__ == "__main__":
    main()

